/*
 *  test_fail.sli
 *
 *  This file is part of NEST.
 *
 *  Copyright (C) 2004 The NEST Initiative
 *
 *  NEST is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  NEST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with NEST.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/** @BeginDocumentation
Name: testsuite::test_fail - test if SLI returns exit code 126 when executing a file with unhandled errors.

Synopsis: (test_fail) run ->

Description:
This script provokes an error that is not handled by any user error
handler. It is used to test if SLI quits with exit code 126 after
executing a file that contains errors.

Author: Ruediger Kupper

FirstVersion: 03-jul-2008

Remarks:
Yes, this script is really meant to fail!

SeeAlso: testsuite::test_pass, testsuite::test_fail, testsuite::test_stop, testsuite::test_goodhandler,  testsuite::test_lazyhandler, testsuite::test_badhandler
*/

% Yes, this script fails. This is intentional. Really.
% And no, there shall be no stopped context around this error. Really. It simply fails. That's all.

%provoke an error:
1 0 div
